\LoadClass[11pt]{report}

\usepackage{graphicx}
\usepackage{titlesec}
\usepackage{wrapfig}
\usepackage{url}
\usepackage{subfiles}
\usepackage[titletoc]{appendix}
\usepackage[a4paper]{geometry}
\usepackage{caption}
\usepackage{array}

\titleformat{\chapter}
  {\Large\bfseries} % format
  {}                % label
  {0pt}             % sep
  {\huge}           % before-code
  
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}
